spring.application.name=restaurant-roulette
server.address=0.0.0.0
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/randish;MODE=PostgreSQL;DATABASE_TO_UPPER=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.sql.init.mode=always
spring.h2.console.enabled=true
